spring:
  datasource:
    url: jdbc:postgresql://localhost:5460/budgetapp
    username: postgres
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true