server:
  port: 8080

spring:
  jpa:
    show-sql: true

---

spring:
  profiles: default
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
  flyway:
    enabled: false

---

spring:
  profiles: local
  datasource:
    url: jdbc:postgresql://localhost:5460/budgetapp
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true

---

spring:
  profiles: heroku
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  flyway:
    enabled: true